[settings]
lockfile = true
experimental = true
paranoid = false
aqua.github_attestations = false
aqua.cosign = false
aqua.slsa = false
aqua.minisign = false
idiomatic_version_file_enable_tools = ["python"]

[tools]
"aqua:nektos/act" = "0.2.65"
"aqua:casey/just" = "1.42.4"
"github:nushell/nushell" = "0.107.0"
"aqua:astral-sh/uv" = "0.6.14"
