[settings]
locked = true
github.slsa = false
lockfile = true
experimental = true
paranoid = false
github.github_attestations = false
aqua.github_attestations = false
aqua.cosign = false
aqua.slsa = false
aqua.minisign = false

[tools]
"aqua:go-task/task" = "3.45.4"
"github:bufbuild/buf" = "1.34.0"
