[settings]
locked = true
github.slsa = false
lockfile = true
experimental = true
paranoid = false
github.github_attestations = false
aqua.github_attestations = false
aqua.cosign = false
aqua.slsa = false
aqua.minisign = false

[tools]
"aqua:GoogleContainerTools/skaffold" = "2.13.2"
"aqua:getsops/sops" = "3.9.1"
"aqua:viaduct-ai/kustomize-sops" = "4.3.2"
"aqua:kubernetes/kubernetes/kubectl" = "1.31.2"
"aqua:kubernetes-sigs/kind" = "0.30.0"
